name: CI CD

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: ./.github/workflows/release.yaml

  checks:
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    uses: ./.github/workflows/checks.yaml

  deploy:
    needs: checks
    uses: ./.github/workflows/deploy.yaml
